import {nanoid} from 'nanoid/non-secure';
import menone from '../assets/images/menone.png';
import womenone from '../assets/images/womenone.png';
import bikeone from '../assets/images/bikeone.png';
import carone from '../assets/images/carone.png';
import electricianone from '../assets/images/electricianone.png';
import acone from '../assets/images/acone.png';
import plumberone from '../assets/images/plumberone.png';
import carpenterone from '../assets/images/carpenterone.png';
import mentwo from '../assets/images/mentwo.png';
import womentwo from '../assets/images/womentwo.png';
import biketwo from '../assets/images/biketwo.png';
import cartwo from '../assets/images/cartwo.png';
import electriciantwo from '../assets/images/electriciantwo.png';
import actwo from '../assets/images/actwo.png';
import plumbertwo from '../assets/images/plumbertwo.png';
import carpentertwo from '../assets/images/carpentertwo.png';
import menthree from '../assets/images/menthree.png';
import womenthree from '../assets/images/womenthree.png';
import bikethree from '../assets/images/bikethree.png';
import carthree from '../assets/images/carthree.png';
import electricianthree from '../assets/images/electricianthree.png';
import acthree from '../assets/images/acthree.png';
import plumberthree from '../assets/images/plumberthree.png';
import carpenterthree from '../assets/images/carpenterthree.png';
import electricianfour from '../assets/images/electricianfour.png';
import carpenterfour from '../assets/images/carpenterfour.png';
import plumberfour from '../assets/images/plumberfour.png';
const shopData = [
  {
    shopId: nanoid(),
    name: 'Rolex Salon',
    phoneNumber: '+91-9800858846',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Hair cut',
          price: 10,
          duration: '40 Mins',
          img: womenone,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '60 Mins',
          img: womentwo,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Haircut & Shave',
          price: 40,
          duration: '60 Mins',
          img: womenone,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '60 Mins',
          img: womentwo,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenthree,
        },
      ],
    },
    rating: 5,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Woman only',
    priceRange: '$$',
    serviceType: 'Women Beauty',
    image: womenone,
    discount: 40,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=22.5726,88.3639',
  },
  {
    shopId: nanoid(),
    name: 'Another Salon Name',
    phoneNumber: '987-654-3210',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 10,
          duration: '40 Mins',
          img: womenone,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '60 Mins',
          img: womentwo,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Men Beauty',
          price: 40,
          duration: '60 Mins',
          img: womenone,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '60 Mins',
          img: womentwo,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenthree,
        },
      ],
    },
    rating: 4.3,
    location: 'Another location',
    distance: 6.5,
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Women only',
    priceRange: '$$',
    serviceType: 'Women Beauty',
    image: womentwo,
    discount: 30,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.8615',
  },

  {
    shopId: nanoid(),
    name: 'Woodlands Hills Salon',
    phoneNumber: '123-456-7890',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 40,
          duration: '40 Mins',
          img: menone,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '20 Mins',
          img: mentwo,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '10 Mins',
          img: menthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Women Beauty',
          price: 40,
          duration: '60 Mins',
          img: mentwo,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '40 Mins',
          img: menthree,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: menone,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men only',
    priceRange: '$$',
    serviceType: 'Men Beauty',
    image: menone,
    discount: 50,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.0719',
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Salon',
    phoneNumber: '123-456-7890',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 40,
          duration: '40 Mins',
          img: menone,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '20 Mins',
          img: mentwo,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '10 Mins',
          img: menthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Haircut & Shave',
          price: 40,
          duration: '60 Mins',
          img: menone,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '40 Mins',
          img: menthree,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: menone,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    priceRange: '$$',
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men & Woman',
    serviceType: 'Men Beauty',
    image: mentwo,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.0719',
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Electric',
    phoneNumber: '444-555-6666',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Wiring',
          price: 40,
          duration: '30 Mins',
          img: electricianone,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electriciantwo,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electricianthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electriciantwo,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electricianthree,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electricianfour,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    overview: 'All type electric service',
    serviceFor: 'House',
    distance: 5.0,
    priceRange: '$$',
    serviceType: 'Electrician',
    image: electricianfour,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.0719',
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Electric',
    phoneNumber: '444-555-6666',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Wiring',
          price: 40,
          duration: '30 Mins',
          img: electricianone,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electriciantwo,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electricianthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electriciantwo,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electricianthree,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electricianfour,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'All type electric service',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Electrician',
    image: electricianone,
    discount: 60,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.0719',
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Carpenter',
    phoneNumber: '123-555-6789',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Whole House',
          price: 40,
          duration: '60 Mins',
          img: carpenterone,
        },
        {
          id: nanoid(),
          name: 'Cabinets',
          price: 40,
          duration: '50 Mins',
          img: carpentertwo,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterfour,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterone,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpentertwo,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'wooden furniture',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Carpenter',
    image: carpenterone,
    googleMapsUrl:
      'https://www.google.com/maps/dir/?api=1&destination=23.2324,87.0719',
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Carpenter',
    phoneNumber: '123-555-6789',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Whole House',
          price: 40,
          duration: '60 Mins',
          img: carpenterone,
        },
        {
          id: nanoid(),
          name: 'Cabinets',
          price: 40,
          duration: '50 Mins',
          img: carpentertwo,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterfour,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenterone,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpentertwo,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'metal, wooden, plastic appliances',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Carpenter',
    image: carpenterthree,
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Plumber',
    phoneNumber: '321-555-8765',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberone,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '20 Mins',
          img: plumbertwo,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '10 Mins',
          img: plumberthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberfour,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberone,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumbertwo,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'water change',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Plumber',
    image: plumberone,
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Plumber',
    phoneNumber: '321-555-8765',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberone,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '20 Mins',
          img: plumbertwo,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '10 Mins',
          img: plumberthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberfour,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumberone,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumbertwo,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: 5.0,
    overview: 'water change',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Plumber',
    image: plumberfour,
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Bike Mechanic',
    phoneNumber: '111-555-2222',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Tire Replacement',
          price: 30,
          duration: '30 Mins',
          img: bikeone,
        },
        {
          id: nanoid(),
          name: 'Engine Oil Change',
          price: 20,
          duration: '20 Mins',
          img: biketwo,
        },
        {
          id: nanoid(),
          name: 'Full Bike Service',
          price: 50,
          duration: '90 Mins',
          img: bikethree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Tire & Brake Check',
          price: 40,
          duration: '60 Mins',
          img: bikeone,
        },
        {
          id: nanoid(),
          name: 'Full Service & Polishing',
          price: 60,
          duration: '120 Mins',
          img: biketwo,
        },
        {
          id: nanoid(),
          name: 'Bike Cleaning & Lubrication',
          price: 25,
          duration: '45 Mins',
          img: bikethree,
        },
      ],
    },
    rating: 4.2,
    location: 'Downtown',
    distance: 4.0,
    overview: 'Tire replacement, Engine oil change, Full bike service',
    serviceFor: 'Bikes',
    priceRange: '$$',
    serviceType: 'Bike Mechanic',
    image: bikeone,
  },
  {
    shopId: nanoid(),
    name: 'Downtown Bike Fix',
    phoneNumber: '123-777-8888',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Chain Replacement',
          price: 25,
          duration: '30 Mins',
          img: bikeone,
        },
        {
          id: nanoid(),
          name: 'Brake Adjustment',
          price: 15,
          duration: '20 Mins',
          img: biketwo,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Complete Bike Overhaul',
          price: 100,
          duration: '180 Mins',
          img: bikethree,
        },
        {
          id: nanoid(),
          name: 'Brake & Tire Combo Service',
          price: 50,
          duration: '90 Mins',
          img: bikeone,
        },
      ],
    },
    rating: 4.0,
    location: 'City Center',
    distance: 6.0,
    overview: 'Chain replacement, Brake adjustment, Full bike service',
    serviceFor: 'Bikes',
    priceRange: '$$',
    serviceType: 'Bike Mechanic',
    image: bikethree,
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills Car Mechanic',
    phoneNumber: '222-555-3333',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Brake Repair',
          price: 80,
          duration: '90 Mins',
          img: carone,
        },
        {
          id: nanoid(),
          name: 'Car Washing',
          price: 50,
          duration: '45 Mins',
          img: cartwo,
        },
        {
          id: nanoid(),
          name: 'Engine Service',
          price: 120,
          duration: '120 Mins',
          img: carthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Engine & Brake Service',
          price: 150,
          duration: '180 Mins',
          img: carone,
        },
        {
          id: nanoid(),
          name: 'Full Car Inspection',
          price: 200,
          duration: '240 Mins',
          img: carthree,
        },
        {
          id: nanoid(),
          name: 'Tire Replacement & Wheel Alignment',
          price: 100,
          duration: '120 Mins',
          img: cartwo,
        },
      ],
    },
    rating: 4.5,
    location: 'City Center',
    distance: 8.0,
    overview: 'Brake repair, Car washing, Engine service',
    serviceFor: 'Cars',
    priceRange: '$$$',
    serviceType: 'Car Mechanic',
    image: carone,
  },
  {
    shopId: nanoid(),
    name: 'Uptown Car Repair',
    phoneNumber: '333-888-7777',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Tire Replacement',
          price: 60,
          duration: '60 Mins',
          img: cartwo,
        },
        {
          id: nanoid(),
          name: 'Battery Replacement',
          price: 90,
          duration: '60 Mins',
          img: carthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Complete Car Service',
          price: 250,
          duration: '300 Mins',
          img: carone,
        },
        {
          id: nanoid(),
          name: 'Engine Tune-Up & Oil Change',
          price: 180,
          duration: '150 Mins',
          img: carthree,
        },
      ],
    },
    rating: 4.6,
    location: 'Uptown',
    distance: 10.0,
    overview: 'Tire replacement, Battery replacement, Full car service',
    serviceFor: 'Cars',
    priceRange: '$$$',
    serviceType: 'Car Mechanic',
    image: carthree,
  },
  {
    shopId: nanoid(),
    name: 'Woodlands Hills AC & Refrigerator Mechanic',
    phoneNumber: '333-555-4444',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'AC Gas Refilling',
          price: 60,
          duration: '60 Mins',
          img: acone,
        },
        {
          id: nanoid(),
          name: 'Refrigerator Compressor Repair',
          price: 100,
          duration: '90 Mins',
          img: actwo,
        },
        {
          id: nanoid(),
          name: 'AC & Refrigerator Cleaning',
          price: 50,
          duration: '60 Mins',
          img: acthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'AC Service Package',
          price: 120,
          duration: '120 Mins',
          img: acone,
        },
        {
          id: nanoid(),
          name: 'Fridge Service Package',
          price: 140,
          duration: '150 Mins',
          img: acthree,
        },
        {
          id: nanoid(),
          name: 'AC & Fridge Annual Maintenance',
          price: 200,
          duration: '240 Mins',
          img: actwo,
        },
      ],
    },
    rating: 4.3,
    location: 'Uptown',
    distance: 6.0,
    overview: 'AC gas refilling, Refrigerator compressor repair, Cleaning',
    serviceFor: 'Home Appliances',
    priceRange: '$$$',
    serviceType: 'AC & Refrigerator',
    image: acone,
  },
  {
    shopId: nanoid(),
    name: 'City Center Cooling Services',
    phoneNumber: '444-999-8888',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Refrigerator Gas Refill',
          price: 70,
          duration: '60 Mins',
          img: actwo,
        },
        {
          id: nanoid(),
          name: 'AC Installation',
          price: 150,
          duration: '120 Mins',
          img: acthree,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'AC & Refrigerator Combo Service',
          price: 180,
          duration: '180 Mins',
          img: acone,
        },
        {
          id: nanoid(),
          name: 'Fridge Deep Cleaning & Repair',
          price: 110,
          duration: '90 Mins',
          img: acthree,
        },
      ],
    },
    rating: 4.4,
    location: 'City Center',
    distance: 7.0,
    overview: 'Fridge gas refill, AC installation, Repair and maintenance',
    serviceFor: 'Home Appliances',
    priceRange: '$$$',
    serviceType: 'AC & Refrigerator',
    image: actwo,
  },
];

export default shopData;
