import {nanoid} from 'nanoid/non-secure';
import menBeauty from '../assets/imageIcons/barbershop.png';
import womenBeauty from '../assets/imageIcons/beauty.png';
import bike from '../assets/imageIcons/motorcycle.png';
import car from '../assets/imageIcons/mechanic.png';
import electrician from '../assets/imageIcons/electrician.png';
import ac from '../assets/imageIcons/airconditioner.png';
import plumber from '../assets/imageIcons/wrenchtool.png';
import carpenter from '../assets/imageIcons/carpenter.png';
const shopData = [
  {
    id: 1,
    name: 'Woodlands Hills Salon',
    phoneNumber: '123-456-7890',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Hair cut',
          price: 10,
          duration: '40 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Haircut & Shave',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men & Woman',
    priceRange: '$$',
    serviceType: 'Women Beauty',
    image: womenBeauty,
  },
  {
    id: 2,
    name: 'Another Salon Name',
    phoneNumber: '987-654-3210',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 10,
          duration: '40 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Men Beauty',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: womenBeauty,
        },
      ],
    },
    rating: 4.3,
    location: 'Another location',
    distance: '6.5 Kms',
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men & Woman',
    priceRange: '$$',
    serviceType: 'Women Beauty',
    image: womenBeauty,
  },

  {
    id: 5,
    name: 'Woodlands Hills Salon',
    phoneNumber: '123-456-7890',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 40,
          duration: '40 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '20 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '10 Mins',
          img: menBeauty,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Women Beauty',
          price: 40,
          duration: '60 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '40 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: menBeauty,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men & Woman',
    priceRange: '$$',
    serviceType: 'Men Beauty',
    image: menBeauty,
  },
  {
    id: 6,
    name: 'Woodlands Hills Salon',
    phoneNumber: '123-456-7890',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Haircut',
          price: 40,
          duration: '40 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Body Massage',
          price: 40,
          duration: '20 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Active Detox Cleanup',
          price: 40,
          duration: '10 Mins',
          img: menBeauty,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Haircut & Shave',
          price: 40,
          duration: '60 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Beard Grooming',
          price: 40,
          duration: '40 Mins',
          img: menBeauty,
        },
        {
          id: nanoid(),
          name: 'Haircut & Anti-Pollution Cleanup',
          price: 40,
          duration: '60 Mins',
          img: menBeauty,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    priceRange: '$$',
    overview: 'Haircut, Spa, Massage',
    serviceFor: 'Men & Woman',
    serviceType: 'Men Beauty',
    image: menBeauty,
  },
  {
    id: 7,
    name: 'Woodlands Hills Electric',
    phoneNumber: '444-555-6666',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Wiring',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    overview: 'All type electric service',
    serviceFor: 'House',
    distance: '5.0 Kms',
    priceRange: '$$',
    serviceType: 'Electrician',
    image: electrician,
  },
  {
    id: 8,
    name: 'Woodlands Hills Electric',
    phoneNumber: '444-555-6666',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Wiring',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Light Change',
          price: 40,
          duration: '30 Mins',
          img: electrician,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
        {
          id: nanoid(),
          name: 'Wiring & Light',
          price: 40,
          duration: '60 Mins',
          img: electrician,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'All type electric service',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Electrician',
    image: electrician,
  },
  {
    id: 9,
    name: 'Woodlands Hills Carpenter',
    phoneNumber: '123-555-6789',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Whole House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Cabinets',
          price: 40,
          duration: '50 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'wooden furniture',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Carpenter',
    image: carpenter,
  },
  {
    id: 10,
    name: 'Woodlands Hills Carpenter',
    phoneNumber: '123-555-6789',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Whole House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Cabinets',
          price: 40,
          duration: '50 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
        {
          id: nanoid(),
          name: 'Wooden House',
          price: 40,
          duration: '60 Mins',
          img: carpenter,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'metal, wooden, plastic appliances',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Carpenter',
    image: carpenter,
  },
  {
    id: 11,
    name: 'Woodlands Hills Plumber',
    phoneNumber: '321-555-8765',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '20 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '10 Mins',
          img: plumber,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'water change',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Plumber',
    image: plumber,
  },
  {
    id: 12,
    name: 'Woodlands Hills Plumber',
    phoneNumber: '321-555-8765',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '20 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '10 Mins',
          img: plumber,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
        {
          id: nanoid(),
          name: 'Water Change',
          price: 40,
          duration: '40 Mins',
          img: plumber,
        },
      ],
    },
    rating: 4.1,
    location: 'Keira throughway',
    distance: '5.0 Kms',
    overview: 'water change',
    serviceFor: 'House',
    priceRange: '$$',
    serviceType: 'Plumber',
    image: plumber,
  },
  {
    id: 13,
    name: 'Woodlands Hills Bike Mechanic',
    phoneNumber: '111-555-2222',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Tire Replacement',
          price: 30,
          duration: '30 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Engine Oil Change',
          price: 20,
          duration: '20 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Full Bike Service',
          price: 50,
          duration: '90 Mins',
          img: bike,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Tire & Brake Check',
          price: 40,
          duration: '60 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Full Service & Polishing',
          price: 60,
          duration: '120 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Bike Cleaning & Lubrication',
          price: 25,
          duration: '45 Mins',
          img: bike,
        },
      ],
    },
    rating: 4.2,
    location: 'Downtown',
    distance: '4.0 Kms',
    overview: 'Tire replacement, Engine oil change, Full bike service',
    serviceFor: 'Bikes',
    priceRange: '$$',
    serviceType: 'Bike Mechanic',
    image: bike,
  },
  {
    id: 14,
    name: 'Downtown Bike Fix',
    phoneNumber: '123-777-8888',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Chain Replacement',
          price: 25,
          duration: '30 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Brake Adjustment',
          price: 15,
          duration: '20 Mins',
          img: bike,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Complete Bike Overhaul',
          price: 100,
          duration: '180 Mins',
          img: bike,
        },
        {
          id: nanoid(),
          name: 'Brake & Tire Combo Service',
          price: 50,
          duration: '90 Mins',
          img: bike,
        },
      ],
    },
    rating: 4.0,
    location: 'City Center',
    distance: '6.0 Kms',
    overview: 'Chain replacement, Brake adjustment, Full bike service',
    serviceFor: 'Bikes',
    priceRange: '$$',
    serviceType: 'Bike Mechanic',
    image: bike,
  },
  {
    id: 15,
    name: 'Woodlands Hills Car Mechanic',
    phoneNumber: '222-555-3333',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Brake Repair',
          price: 80,
          duration: '90 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Car Washing',
          price: 50,
          duration: '45 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Engine Service',
          price: 120,
          duration: '120 Mins',
          img: car,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Engine & Brake Service',
          price: 150,
          duration: '180 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Full Car Inspection',
          price: 200,
          duration: '240 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Tire Replacement & Wheel Alignment',
          price: 100,
          duration: '120 Mins',
          img: car,
        },
      ],
    },
    rating: 4.5,
    location: 'City Center',
    distance: '8.0 Kms',
    overview: 'Brake repair, Car washing, Engine service',
    serviceFor: 'Cars',
    priceRange: '$$$',
    serviceType: 'Car Mechanic',
    image: car,
  },
  {
    id: 16,
    name: 'Uptown Car Repair',
    phoneNumber: '333-888-7777',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Tire Replacement',
          price: 60,
          duration: '60 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Battery Replacement',
          price: 90,
          duration: '60 Mins',
          img: car,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'Complete Car Service',
          price: 250,
          duration: '300 Mins',
          img: car,
        },
        {
          id: nanoid(),
          name: 'Engine Tune-Up & Oil Change',
          price: 180,
          duration: '150 Mins',
          img: car,
        },
      ],
    },
    rating: 4.6,
    location: 'Uptown',
    distance: '10.0 Kms',
    overview: 'Tire replacement, Battery replacement, Full car service',
    serviceFor: 'Cars',
    priceRange: '$$$',
    serviceType: 'Car Mechanic',
    image: car,
  },
  {
    id: 17,
    name: 'Woodlands Hills AC & Refrigerator Mechanic',
    phoneNumber: '333-555-4444',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'AC Gas Refilling',
          price: 60,
          duration: '60 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'Refrigerator Compressor Repair',
          price: 100,
          duration: '90 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'AC & Refrigerator Cleaning',
          price: 50,
          duration: '60 Mins',
          img: ac,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'AC Service Package',
          price: 120,
          duration: '120 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'Fridge Service Package',
          price: 140,
          duration: '150 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'AC & Fridge Annual Maintenance',
          price: 200,
          duration: '240 Mins',
          img: ac,
        },
      ],
    },
    rating: 4.3,
    location: 'Uptown',
    distance: '6.0 Kms',
    overview: 'AC gas refilling, Refrigerator compressor repair, Cleaning',
    serviceFor: 'Home Appliances',
    priceRange: '$$$',
    serviceType: 'AC & Refrigerator',
    image: ac,
  },
  {
    id: 18,
    name: 'City Center Cooling Services',
    phoneNumber: '444-999-8888',
    services: {
      recommended: [
        {
          id: nanoid(),
          name: 'Refrigerator Gas Refill',
          price: 70,
          duration: '60 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'AC Installation',
          price: 150,
          duration: '120 Mins',
          img: ac,
        },
      ],
      packages: [
        {
          id: nanoid(),
          name: 'AC & Refrigerator Combo Service',
          price: 180,
          duration: '180 Mins',
          img: ac,
        },
        {
          id: nanoid(),
          name: 'Fridge Deep Cleaning & Repair',
          price: 110,
          duration: '90 Mins',
          img: ac,
        },
      ],
    },
    rating: 4.4,
    location: 'City Center',
    distance: '7.0 Kms',
    overview: 'Fridge gas refill, AC installation, Repair and maintenance',
    serviceFor: 'Home Appliances',
    priceRange: '$$$',
    serviceType: 'AC & Refrigerator',
    image: ac,
  },
];

export default shopData;
